### ISSUE TITLE
[Installation] Prerequis serveur manque python et git

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-rando#809]
Pour que l'installation des paquets npm fonctionne il faut avoir git et python d'installé. Ce serait bien de compléter la documentation.

Si git est absent :
```
npm ERR! git clone --template=.npm/_git-remotes/_templates --mirror https://github.com/bastyen/Leaflet-MiniMap.git .npm/_git-remotes/git-https-github-com-bastyen-Leaflet-MiniMap-git-fe3ba7d1ffcc9b6ad6924c760629a9af4e412b4d-267e67a8: undefined
npm ERR! git clone --template=.npm/_git-remotes/_templates --mirror https://github.com/makinacorpus/rando3D.git .npm/_git-remotes/git-https-github-com-makinacorpus-rando3D-git-970e257806a247f274ef80abfd5e07671e3c4db3-2ef0830d: undefined

```

Si python est absent :
```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (.nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at .nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (.nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (.nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at .nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at .nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at .nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 5.4.55-1-pve
gyp ERR! command ".nvm/versions/node/v6.14.3/bin/node" ".nvm/versions/node/v6.14.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd apps/Geotrek-rando-2.30.0/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v6.14.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

```

**Comment by gutard** [comment]
Merci pour l'info. J'ai un peu de mal à voir pourquoi on a besoin de python. On découvre le problème parce que maintenant l'exécutable installé par défaut est python3 et non plus python.
